on:
  push:

jobs:
  run:
    strategy:
      matrix:
        runs-on: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.11", "3.12"]
        cmd: ["uv pip install --system", "pip install"]       
      fail-fast: false 

    runs-on: ${{ matrix.runs-on }}
        
    steps:
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false

      - name: Do an install
        run: |
          ${{ matrix.cmd }} pvxslibs==1.3.2 p4p==4.2.0 --no-binary p4p --no-binary pvxslibs && pip freeze

      - name: Check it works
        run: |
          python -c "from p4p import *"
  